sudo: false
language: php

jobs:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
      env: COMPOSER_OPTION=--ignore-platform-reqs

cache:
  directories:
    - vendor

before_script:
  - travis_retry composer install --no-interaction --no-suggest $COMPOSER_OPTION
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

script:
  - vendor/bin/phpunit
