sudo: false
language: php
dist: xenial

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - travis_retry composer install --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT

script:
  - vendor/bin/phpunit
