name: tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3, 8.4, 8.5]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring
          coverage: xdebug

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: composer run test:coverage

      - name: Code Coverage
        uses: qltysh/qlty-action/coverage@c9b09987143d1e4ac955f4803c7bea742102feb5 # v2.4.0
        with:
          oidc: true
          files: build/logs/clover.xml
